package org.arya.banking.common.constants;

public interface ResponseCodes {

    String USER_CREATED_201 = "USER_CREATED_201";
    String USER_UPDATED_200 = "USER_UPDATED_200";
    String SECURITY_DETAILS_UPDATED_200 = "SECURITY_DETAILS_UPDATED_200";
    String KEYCLOAK_ROLE_CREATED_200 = "KEYCLOAK_ROLE_CREATED_200";
    String VAULT_SECRET_CREATED_200 = "VAULT_SECRET_CREATED_200";
    String VAULT_SECRET_DELETED_200 = "VAULT_SECRET_DELETED_200";
    String VAULT_SECRET_UPDATED_200 = "VAULT_SECRET_UPDATED_200";
}
