package org.arya.banking.common.exception;

public interface ExceptionCode {

    String AUTH_KEYCLOAK_INTERNAL_SERVER_ERROR_500 = "AUTH_KEYCLOAK_INTERNAL_SERVER_ERROR_500";
    String AUTH_KEYCLOAK_USER_CREATION_FAILED_400 = "AUTH_KEYCLOAK_USER_CREATION_FAILED_400";

    String USER_ALREADY_EXISTS_409 = "USER_ALREADY_EXISTS_409";
    String USER_NOT_FOUND_404 = "USER_NOT_FOUND_404";

    String AUTH_INVALID_OAUTH_TOKEN_400 = "AUTH_INVALID_OAUTH_TOKEN_400";
    String SECURITY_DETAILS_NOT_FOUND_404 = "SECURITY_DETAILS_NOT_FOUND_404";
    String SECURITY_INVALID_CREDENTIALS_401 = "SECURITY_INVALID_CREDENTIALS_401";
    String ACCOUNT_LOCKED_403 = "ACCOUNT_LOCKED_403";
}
