package org.arya.banking.common.core.exception;

public interface ExceptionCode {

    String AUTH_KEYCLOAK_INTERNAL_SERVER_ERROR_500 = "AUTH_KEYCLOAK_INTERNAL_SERVER_ERROR_500";
    String AUTH_KEYCLOAK_USER_CREATION_FAILED_400 = "AUTH_KEYCLOAK_USER_CREATION_FAILED_400";

    String USER_ALREADY_EXISTS_409 = "USER_ALREADY_EXISTS_409";
    String USER_NOT_FOUND_404 = "USER_NOT_FOUND_404";

    String AUTH_INVALID_OAUTH_TOKEN_400 = "AUTH_INVALID_OAUTH_TOKEN_400";
    String SECURITY_DETAILS_NOT_FOUND_404 = "SECURITY_DETAILS_NOT_FOUND_404";
    String SECURITY_INVALID_CREDENTIALS_401 = "SECURITY_INVALID_CREDENTIALS_401";
    String ACCOUNT_LOCKED_403 = "ACCOUNT_LOCKED_403";

    String ADMIN_KEYCLOAK_CLIENT_ALREADY_EXISTS_409 = "KEYCLOAK_CLIENT_ALREADY_EXISTS_409";
    String ADMIN_KEYCLOAK_CLIENT_CREATION_EXCEPTION_500 = "ADMIN_KEYCLOAK_CLIENT_CREATION_EXCEPTION_500";
    String ADMIN_UN_AUTHORIZED_EXCEPTION_403 = "ADMIN_UN_AUTHORIZED_EXCEPTION_403";
    String ADMIN_KEYCLOAK_REALM_ROLE_ALREADY_EXISTS_409 = "ADMIN_KEYCLOAK_REALM_ROLE_ALREADY_EXISTS_409";
    String ADMIN_KEYCLOAK_REALM_ROLE_NOT_FOUND_404 = "ADMIN_KEYCLOAK_REALM_ROLE_NOT_FOUND_404";
    String ADMIN_VAULT_ROLE_ID_EXCEPTION_403 = "ADMIN_VAULT_ROLE_ID_EXCEPTION_403";
    String ADMIN_VAULT_APPROLE_CREATION_EXCEPTION_400 = "ADMIN_VAULT_APPROLE_CREATION_EXCEPTION_400";
    String ADMIN_VAULT_SECRET_ID_EXCEPTION_403 = "ADMIN_VAULT_SECRET_ID_EXCEPTION_403";
    String VAULT_SECRET_NOT_FOUND_EXCEPTION_404 = "VAULT_SECRET_NOT_FOUND_EXCEPTION_404";
}
