name: Build and Package Application (with repo settings.xml)

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your app source code
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Build the project using the committed settings.xml
      - name: Build and Package the Application
        run: mvn clean deploy -s settings.xml
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      # Step 5: Extract version from pom.xml
      - name: Extract version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Step 6: Create and push tag
      - name: Create and push tag
        if: github.event_name == 'push' && success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"
